version: '3'

services:
  app:
    build: .
    container_name: app-golang
    restart: always
    ports:
      - 9090:9090
    environment:
      - SERVER_PORT=9090
      - DB_HOST=mysql-database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=password123
      - DB_NAME=testapp
    volumes:
      - ./config.json:/config.json

  mysql:
    container_name: mysql-database
    image: mysql:8.0
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password123
    restart: always
